name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake lcov

      - name: Configure and Build
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug
          cmake --build .

      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Generate Coverage
        run: |
          cd build
          gcovr --exclude-unreachable-branches --exclude-throw-branches \
                --exclude '/usr/.*' --exclude '.*/tests/.*' \
                --root .. --xml --output coverage.xml
